# Generated by Django 3.2.12 on 2023-08-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20230807_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_description',
            name='jd_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employer_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Applied_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_text', models.TextField(max_length=2000)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_score', models.IntegerField()),
                ('resume_rank', models.IntegerField()),
                ('resume_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100)),
                ('resume_summary', models.TextField(max_length=2000)),
                ('resume_rank_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_selected', models.BooleanField(default=False)),
                ('jd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_id', to='hr.job_description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
