# Generated by Django 3.2.12 on 2023-08-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20230809_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_resume',
            name='resume_text',
        ),
    ]
