# Generated by Django 3.2.12 on 2023-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20230810_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_credentials',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_credentials',
            name='test_taken',
            field=models.BooleanField(default=False),
        ),
    ]
