# Generated by Django 3.2.12 on 2023-08-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20230810_0147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application_status',
        ),
    ]
