# Generated by Django 3.2.12 on 2023-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_delete_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_credentials',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
