# Generated by Django 3.2.12 on 2023-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_test_credentials_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_credentials',
            old_name='score',
            new_name='test_score',
        ),
        migrations.AddField(
            model_name='test_credentials',
            name='audio_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_credentials',
            name='response_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_credentials',
            name='response_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
