# Generated by Django 3.2.12 on 2023-08-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20230814_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_credentials',
            old_name='response_summary',
            new_name='response',
        ),
    ]
