# Generated by Django 3.2.12 on 2023-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_rename_response_summary_test_credentials_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_resume',
            name='resume_rank_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
